### ISSUE TITLE
感谢开发，卸载了其余所有fonts插件。反馈一个问题

### ISSUE THREAD

**Issue by GamenRoll** [BlackGlory/appoint-font#1]
```
Chrome版本 59.0.3071.115（正式版本） （64 位）
字体 
Standard: 【Noto Serif CJK SC】
Fixed-width: 【Noto Sans Mono CJK SC Regular】
```

大约有30%的情况，网页加载指定字体会失败。
第一次刷新后，成功加载的占90%；
第二次刷新后，成功加载的占9%；
极个别需要刷新3次。

**Comment by BlackGlory** [comment]
研究了2天, 深切地感受到到这个问题不是能轻易解决的.

原先字体偶尔会加载失败这一点我是知道的, 是Chrome自身的问题, 由于标准字体和等宽字体的内容可能会重复, 所以Chrome有时候会由于某种神秘的原因, 将等宽字体优先于标准字体进行渲染, 所以字体会被渲染成等宽字体, 而不是我们想要的标准字体, 这就造成了原先的字体加载失败(视觉上).

现在发现了一个新的问题, 就是Chrome不知道从哪个版本开始, 对Noto Sans Mono CJK SC Regular这样带有字重的字体无法作为一个完整的字体来对待, 所以Noto Sans Mono CJK SC Regular会无法覆盖所有的字体, 最后字体会fallback回缺省字体, 也就是真正意义上字体加载失败的情况, 带有字重的字体在一些情况被直接忽略了.

另外当字体被覆盖后, Chrome单个标签的渲染管道似乎存在缓存, 所以直接刷新页面让字体恢复预期是有困难的, 复制页面的URL在新标签页里打开往往就会正常.

我会继续寻找解决问题的方法.

**Comment by BlackGlory** [comment]
刚刚更新了新的版本, 版本号为2017.8.1, 一个小时内会在Chrome应用商店上架.

新版本重写了部分代码, 解决了上文提到的第二个问题, 第一个问题暂时还是无解.

**Comment by shikkoku** [comment]
![a8 n hb_k1 72dg ya1zm](https://user-images.githubusercontent.com/4697177/30274216-07809998-972f-11e7-9892-01fad51a22eb.png)

设置为

Noto Sans CJK SC Regular
Noto Sans Mono CJK SC Regular

这算是正常情况还是？

**Comment by BlackGlory** [comment]
2023年, 似乎Chrome已经解决了第一个问题.
