### ISSUE TITLE
请问该插件是否在 linux 下的 Chrome 浏览器中无效？

### ISSUE THREAD

**Issue by Dcryfm** [BlackGlory/appoint-font#19]
我设置标准字体为 `MiSans`，设置等宽字体为 `CascadiaCode`，任何网页都没有生效。
我之前使用过”强制网页使用自定义字体“这个插件，更改字体在所有网页都生效了。
我的 `Chrome` 版本为 `113.0.5672.63（正式版本）（64 位）`

**Comment by BlackGlory** [comment]
我测试了一下, 主要问题出在Linux预装的字体太少, 大多数页面使用的中文字体都不存在.
Appoint Font的原理是把本地安装过的字体替换为用户设置的字体, 在这种情况下, Appoint Font根本不知道该替换掉什么字体.

在此基础上, Chrome在Linux上处理字体fallback似乎也有问题, 浏览器的字体设置不会被尊重.
举例来说, 当我设置MiSans字体为默认字体时, 浏览器会错误地选择渲染Noto Serif CJK SC.

---

根据上面的测试,安装中文字体理应能够解决此问题, 所以我尝试安装微软雅黑和宋体.
然而, 在我的Ubuntu Server 20.04上, 这不起效果.
具体表现为, 浏览器选择加载微软雅黑, 而不是用户在扩展里设置的字体.

进一步调查后, 发现这是因为浏览器不知为何不能正常加载以本地字体为源的FontFace:
检查`document.fonts`会发现所有FontFace都处于pending状态.

鉴于Chrome在字体方面一贯的糟糕表现, 这可能是一个bug.
受限于Appoint Font的原理, 无法修复.

**Comment by Dcryfm** [comment]
感谢及时回复啊，我用的是基于 ubuntu 的 linux 系统，安装 `.deb` 的 Chrome 才会有字体问题。如果安装的是 `flatpak` 的Chrome，我只用在浏览器中设置字体，所有页面就会按我设置的字体渲染，不知道啥情况。感谢费心解答，我关闭这个问题了。
