### ISSUE TITLE
请求支持在插件 icon 的点击弹窗中修改规则

### ISSUE THREAD

**Issue by leic4u** [BlackGlory/appoint-font#22]
感谢开发者提供这么优秀的字体替换插件。

不过现在修改规则有点不方便，是否可以支持在点击插件图标时，直接弹窗规则配置窗口？

类似于 Dark Reader 那样。

![Clip_2024-05-19_17-08-10](https://github.com/BlackGlory/appoint-font/assets/32786903/bb5ee1b9-7ed1-4cac-9d6b-6f550c1ed3e2)

**Comment by BlackGlory** [comment]
在v2024.0.0里添加了此功能, 但是不像Dark Reader那么好用, 因为修改规则不会同步修改已经打开的标签页上的效果.
根本原因在于此扩展是以全局应用字体设置这一目标设计的, 如果用户打开很多标签页, 同步修改会造成一些性能问题.

只需要在这里添加"删除所有已打开页面上注入的CSS"和"注入新的CSS"的代码即可实现同步修改, 出于上面提到的理由, 我不是很有动力实现它, 但如果有人实现了, 也欢迎提交PR:
https://github.com/BlackGlory/appoint-font/blob/8a62e22c168326bf48e794e1e40e49e4776d9d15/src/background/storage.ts#L19-L22

**Comment by leic4u** [comment]
> 在v2024.0.0里添加了此功能, 但是不像Dark Reader那么好用, 因为修改规则不会同步修改已经打开的标签页上的效果. 根本原因在于此扩展是以全局应用字体设置这一目标设计的, 如果用户打开很多标签页, 同步修改会造成一些性能问题.
> 
> 只需要在这里添加"删除所有已打开页面上注入的CSS"和"注入新的CSS"的代码即可实现同步修改, 出于上面提到的理由, 我不是很有动力实现它, 但如果有人实现了, 也欢迎提交PR:
> 
> https://github.com/BlackGlory/appoint-font/blob/8a62e22c168326bf48e794e1e40e49e4776d9d15/src/background/storage.ts#L19-L22

也就是说目前的方案，对于已经打开的标签页，需要手动刷新一次，就可以让新规则生效嘛？

**Comment by BlackGlory** [comment]
是, 弹出的界面跟专门打开的选项界面功能完全一样.

leic4u ***@***.***> 于 2024年5月20日周一 下午5:28写道：
