### ISSUE TITLE
font-family里system-ui一项导致自定义字体不生效

### ISSUE THREAD

**Issue by nothingshiru** [BlackGlory/appoint-font#23]
已经在该扩展里设置自定义字体，但有些网页还是显示为~~微软雅黑~~ Microsoft YaHei UI。在尝试手动修改网页font-family，发现是因为网页指定了system-ui这一项导致自定义字体不生效。即使我把自定义字体写在system-ui前面，我的字体也不生效。现在我使用脚本把system-ui从font-family中去掉。

钦定字体能解决这个问题吗？

**Comment by BlackGlory** [comment]
据我所知解决不了.
主动设置页面的font-family对于该扩展来说也不是一个可接受的解决方案(曾经采用过, 在Google的很多产品上有性能问题).
你目前采用的方法可能是最好的解决方案了.
