### ISSUE TITLE
OPPO Sans 4.0设置无效

### ISSUE THREAD

**Issue by vvb0762** [BlackGlory/appoint-font#26]
OPPO Sans 4.0: 
https://www.coloros.com/article/A00000074/

插件很好，感谢作者大大，但是测试这个字体无效果，希望在未来可以支持用上😄

**Comment by BlackGlory** [comment]
也许是没有默认样式, 需要手动添加子字体名(可用Bold, Light, Medium, Regular, SemiBold五种):
![image](https://github.com/user-attachments/assets/b24d2524-a345-4520-9d1a-dd6526767760)

效果:
![image](https://github.com/user-attachments/assets/d3ae3521-fd7f-48e8-b09b-492d2ea46fe5)

**Comment by vvb0762** [comment]
感谢作者大大！已经顺利用上啦
