### ISSUE TITLE
设置等宽字体为SF Mono时不生效

### ISSUE THREAD

**Issue by ocsponge** [BlackGlory/appoint-font#9]
设置等宽字体为SF Mono时不生效，其他字体比如ubuntu mono、Andale mono都可以

**Comment by BlackGlory** [comment]
Chrome在字体方面有很多问题, 这是其中的一个
https://stackoverflow.com/questions/68437455/font-face-srclocal-does-not-work-on-some-fonts

不可能通过扩展程序解决.
